name: (make

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: cmake converter
        run: |
          
          pip install cmake_converter
          cmake-converter -s FriishProduce.sln
          cmake -S "" -B "build" -G "Visual Studio 16 2019" -A "x64"
          make -j66
          ls -a
         
      - name: Upload
  # You may pin to the exact commit or the version.
  # uses: Shopify/upload-to-release@c77c9b3e5d288adaef98a7007bf92340ec6ce03b
        uses: Shopify/upload-to-release@v2.0.0
          with:  
          # Artifact name
          name: iyuhreu
          # Path to the file to upload
          path: .
          # Content type for the file
          content-type: # optional, default is application/octet-stream
          # secrets.GITHUB_TOKEN
          repo-token: 
